### ISSUE TITLE
Unexpected indentation for blank lines between statements

### ISSUE THREAD

**Issue by hauserx** [withered-magic/starpls#247] opened 2024-05-09 10:15 UTC
Simple example:
```
def x():
    y = 4

    z = 2
```

Result:

![image](https://github.com/withered-magic/starpls/assets/32371993/7c60701b-d2c7-4874-a10c-9d550b4908dc)

**Comment by withered-magic** [comment] 2024-05-09 10:29
Hmm, do you know what your indentation settings are for your editor? I'm not able to reproduce this running on VSCode with tabs interpreted as four spaces.

**Comment by hauserx** [comment] 2024-05-09 11:44
I am using fresh install of neovim in WSL2 and looks by default it was using windows CRLF endlines... The issue is fixed by using unix endlines. So seems this issue maybe by under windows/when using CRLF endlines.

**Comment by hauserx** [comment] 2024-05-09 15:12
Attaching small script to reproduce the issue:
[test_starpls_crlf.txt](https://github.com/withered-magic/starpls/files/15264009/test_starpls_crlf.txt)

Output:

```
Diagnostics: {
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "diagnostics": [
      {
        "message": "Unexpected indentation",
        "range": {
          "end": {
            "character": 0,
            "line": 3
          },
          "start": {
            "character": 0,
            "line": 3
          }
        },
        "severity": 1,
        "source": "starpls"
      }
    ],
    "uri": "file:///fakepath/sample.bzl",
    "version": 1
  }
}
```

**Comment by withered-magic** [comment] 2024-05-09 16:23
Thank you! I use WSL2 but not with CRLF line endings so admittedly haven't actually tested this too much 😅 I'll try to have a fix out soon, should be straightforward

**Comment by albertocavalcante** [comment] 2024-08-02 14:36
It would be nice to have support for `CRLF` as this [should be valid](https://bazel.build/rules/windows#:~:text=Line%20endings) for Starlark files.

In the meantime I noticed that `buildifier` by default replaces `CRLF` with `LF`.

While this is not supported by `starpls`, I'm simply conveying using `LF` `EOL` for all `starlark` files with the below:

```sh
buildifier -config=off -r .
```

and at `.vscode\settings.json`:

```json
"[starlark]": {
    "files.eol": "\n"
}
```

**Comment by withered-magic** [comment] 2024-12-01 23:39
Sorry for the slow turnaround here, but this should be fixed on latest main now!

**Closed** 2024-12-01 23:38 UTC
